title: KeepWatching Documentation
description: A comprehensive media tracking platform that helps users manage their favorite TV shows and movies.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman