title: KeepWatching!
description: A modern React-based web application for tracking your favorite TV shows and movies. Never lose track of what you're watching or what episode you're on again!
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman